<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2tpdlnf\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2tpdlnf/appProdProjectContainer.php') {
    touch(__DIR__.'/Container2tpdlnf.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container2tpdlnf\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container2tpdlnf\appProdProjectContainer([
    'container.build_hash' => '2tpdlnf',
    'container.build_id' => '5ad2cc58',
    'container.build_time' => 1643643940,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2tpdlnf');
